ORI R1,R0,0XF
ADD R2,R0,R0 #COUNTER TO COUNT NUMBER OF ONES
ORI R3,R0,0X1 #TO COMPARE THE LEASR SIG BIT WITH
for: AND R6,R1,R3 #TO EXTRACT THE LEAST SIG BIT
BEQ R6,R0,next #IF THE LEAST SIG BIT IS 0 THEN DONT ADD
ADDI R2,R2,1 #TO ADD ONE TO THE CONTER
next: SRLI R1,R1,1 #SHIFT RIGHT TO GET THE NEXT LEAST SIG BIT
BNE R1,R0,for #LOOP BACK
terminate: j terminate

